// <auto-generated />
namespace CargoTaxi.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class change_format_DateTime_onDate_inOrder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_format_DateTime_onDate_inOrder));
        
        string IMigrationMetadata.Id
        {
            get { return "202008171312258_change_format_DateTime_onDate_inOrder"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
